name = "infimum"
license = "GPL-v3"
licenselink = "https://github.com/nanxstats/hugo-tanka/blob/master/LICENSE"
description = ""
homepage = "sharpless298.github.io"
tags = []
features = []
min_version = "0.149"

[author]
  name = "Sharpless298"
  homepage = "sharpless298.github.io"

# If porting an existing theme
[original]
  name = "FHVirus"
  homepage = "https://github.com/fhvirus/astoneek"
  repo = "https://github.com/fhvirus/astoneek"
