name = "Astoneek"
license = "GPL-v3"
licenselink = "https://github.com/nanxstats/hugo-tanka/blob/master/LICENSE"
description = ""
homepage = "fhvirus.github.io"
tags = []
features = []
min_version = "0.41"

[author]
  name = "FHVirus"
  homepage = "fhvirus.github.io"

# If porting an existing theme
[original]
  name = "Tanka"
  homepage = "https://github.com/nanxstats/hugo-tanka"
  repo = "https://github.com/nanxstats/hugo-tanka"
