# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Astoneek"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = ""
homepage = "fhvirus.github.io"
tags = []
features = []
min_version = "0.41"

[author]
  name = "FHVirus"
  homepage = "fhvirus.github.io"

# If porting an existing theme
[original]
  name = "Tanka"
  homepage = "https://github.com/nanxstats/hugo-tanka"
  repo = "https://github.com/nanxstats/hugo-tanka"
